apiVersion: v1
kind: Pod
metadata:
  name: test-pod-custom-scheduler
  namespace: default
spec:
  schedulerName: my-scheduler  # This tells K8s to use our custom scheduler
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-with-selector
  namespace: default
spec:
  schedulerName: my-scheduler
  nodeSelector:
    kubernetes.io/hostname: node1  # Example node selector
  containers:
  - name: busybox
    image: busybox:latest
    command: ["sleep", "3600"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-high-resources
  namespace: default
spec:
  schedulerName: my-scheduler
  containers:
  - name: stress
    image: nginx:latest
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1000m"
